### ISSUE TITLE
Accessing locations when using input_doc_tree

### ISSUE THREAD

**Issue by zoggy** [dbuenzli/xmlm#11]
Hello,

`input_doc_tree` has the following signature:
````ocaml
val input_doc_tree : el:(tag -> 'a list -> 'a) -> data:(string -> 'a) -> input -> dtd * 'a
````
would it be possible to provide a variant in which the `el` and `data` functions would also take a location range (`pos * pos`) ? This would be useful to keep original locations in the produced value of type `'a`.

**Comment by dbuenzli** [comment]
I won't add anything to this interface, I will rather remove from it. A good xml parsing combinator library should be devised *on top* of xmlm. Note that you can devise your own functions, [input_doc_tree](https://github.com/dbuenzli/xmlm/blob/dfd546cad07d8cb6370661fccc03d624b5383371/src/xmlm.ml#L904-L932) is not that complex. However I think that the positions returned by the library are anyway not so good. The whole thing should be gradually rewritten with an API in the style of jsonm.
