### ISSUE TITLE
Pure parsing API, that supports streamed reads

### ISSUE THREAD

**Issue by infinity0** [dbuenzli/xmlm#17]
A more extreme form of #16 would be to support a pure interface, something like:

```ocaml
type pure_input = {
  (* similar to the existing input type but pure *)
  unconsumed : string;
}

val parse : string -> pure_input -> (signal list * pure_input)
```

The behaviour of `parse s i0` would be to concatenate `i0.unconsumed ^ s`, apply the existing parse algorithm to this, generating a list of signals and the new input state `i1` with a new `unconsumed` field consisting of the suffix of `s` that it was not able to consume.

This would allow the library to be used in pure code, where the impure reading logic might be happening way further up the stack.

**Comment by dbuenzli** [comment]
See [this comment](https://github.com/dbuenzli/xmlm/issues/16#issuecomment-287379861).
