### ISSUE TITLE
A ?strip option for `make_output` ?

### ISSUE THREAD

**Issue by nojb** [dbuenzli/xmlm#22]
What do you think about adding an option `?strip` to `make_output` analogous to the `?strip` option of `make_input` ? The use-case is that even when one wants indentation in the output, sometimes the whitespace around text nodes causes problems (when the XML is used by consumers that for whatever reason do not trim the text nodes).

Note: I don't claim to understand XML rules relating to whitespace, but without such a flag one is forced to use unindented output for maximum compatibility. And it would be symmetric with the flag for `make_input` :)

I can propose a PR if you think this could be considered for addition.

**Comment by dbuenzli** [comment]
> The use-case is that even when one wants indentation in the output, sometimes the whitespace around text nodes causes problems (when the XML is used by consumers that for whatever reason do not trim the text nodes).

Well these two requirements are conflicting (indentation and lack of whitespace in data). I'm afraid there's no sensible way of handling that automatically, only the producer can know whether whitespace is significant or not in specific tags.

Unless I'm mistaken as a producer you have full control over the output by adding/removing the space you want in your data or idententing it the way you wish manually. So I rather let the client handle this.

**Comment by nojb** [comment]
Fair enough. Thanks.
