### ISSUE TITLE
Function output_tree did not work as expected

### ISSUE THREAD

**Issue by actioplan** [dbuenzli/xmlm#26]
While trying to generate a xml document/entity, the usage of _output_tree_ lead the "start signal not allowed here" runtime error on the first call.

After looking to your source code, it seems to me, that _output_tree_ can't be called without a runtime error, as there is no possibility through parameters to go from depth = -1 to depth = 0.

The obvious workaround for me was to use _output_doc_tree_ with the Dtd set to _None_, which works great, thus I didn't really needed the _output_tree_ function.

Thanks for your great work & kind regards from Stuttgart,

Christophe

**Comment by dbuenzli** [comment]
It's difficult to say anything without a repro case but I suspect you did not output a [well-formed](https://erratique.ch/software/xmlm/doc/Xmlm#TYPEsignal) sequence of signals. 

For example the following example works for me: 
```ocaml 
let li d = `El ((("", "li"), []), [`Data d])
let frag = `El ((("", "ol"), []), [li "bli"; li "bla"; li "blo"])

let main () =
  let b = Buffer.create 233 in
  let o = Xmlm.make_output (`Buffer b) in
  Xmlm.output o (`Dtd None);
  Xmlm.output_tree (fun x -> x) o frag;
  print_endline (Buffer.contents b)

let () = main ()
```

Feel free to reopen and add more details if you meant something else.
